version: '3'
services:
  # dynamodb:
  #   image: tray/dynamodb-local
  #   ports:
  #     - "8000:8000"
  #   command: "-inMemory -port 8000"
  esearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.0"
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  mock-api:
    image: submissions-mock-api:latest
    container_name: submissions-mock-api
    build:
      context: ../
      dockerfile: mock-api/Dockerfile
    ports:
      - "4000:4000"
  # minio1:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     MINIO_ACCESS_KEY: "FAKE_ACCESS_KEY"
  #     MINIO_SECRET_KEY: "FAKE_SECRET_ACCESS_KEY"
  #   command: "server /data"